### ISSUE TITLE
Support Rule Exclusions via CLI

### ISSUE THREAD

**Issue by jshlbrd** [chronicle/detection-rules#100]
It would be really helpful if the rules manager supported [rule exclusions](https://cloud.google.com/chronicle/docs/detection/rule-exclusions). These aren't in YARA-L format, and instead are a chain of conditional statements in text format like: `(principal.process.command_line = /foo/) AND (principal.process.command_line = /bar/)`.

The CLI would need to support reading the text-format files plus assigning the exclusion to existing rules. Hope there's an API for this, because it would be great to be able to have these in code!

**Comment by threat-punter** [comment]
Hey @jshlbrd,

There is an API endpoint ([findingsRefinements](https://cloud.google.com/chronicle/docs/reference/rest/v1alpha/projects.locations.instances.findingsRefinements)) that can be used to manage exclusions for Curated Detections.

I will work on adding support for this to the rule manager tooling.

Here is an example [exclusion](https://cloud.google.com/chronicle/docs/reference/rest/v1alpha/projects.locations.instances.findingsRefinements/get) from my Google SecOps tenant:

```json
{
    "findingsRefinements": [
        {
            "name": "projects/1234567890123/locations/us/instances/32e27911-c58e-4adc-99f1-03652f1a74fd/findingsRefinements/fr_32e27911-c58e-4adc-99f1-03652f1a74fd",
            "displayName": "Lab Hosts",
            "type": "DETECTION_EXCLUSION",
            "createTime": "2025-03-03T16:01:32.286719Z",
            "updateTime": "2025-03-03T16:01:32.286719Z",
            "query": "(principal.hostname = \"lab-desktop-123\")"
        },
    ]
}
```

And here is the exclusion's [deployment state](https://cloud.google.com/chronicle/docs/reference/rest/v1alpha/projects.locations.instances.findingsRefinements/getDeployment):

```json
{
    "name": "projects/1234567890123/locations/us/instances/32e27911-c58e-4adc-99f1-03652f1a74fd/findingsRefinements/fr_32e27911-c58e-4adc-99f1-03652f1a74fd/deployment",
    "enabled": true,
    "updateTime": "2025-03-03T16:01:33.101599Z",
    "detectionExclusionApplication":
    {
        "curatedRules":
        [
            "projects/1234567890123/locations/us/instances/32e27911-c58e-4adc-99f1-03652f1a74fd/curatedRules/ur_7f8204c2-0d54-4dab-b7fa-133f8b94a53b"
        ]
    }
}
```

**Comment by jshlbrd** [comment]
This is great! I'm happy to collaborate on a config design if it's helpful.

**Comment by threat-punter** [comment]
Awesome. I'm thinking that it will make sense to create a class to represent an exclusion object in Google SecOps and then another class to represent the configuration for exclusion objects in a config file. Similar to what we have for rules and reference lists. What do you think?

Classes for a rule and rule configuration: https://github.com/chronicle/detection-rules/blob/main/tools/rule_manager/rule_cli/rules.py#L53-L85

**Comment by jshlbrd** [comment]
> Awesome. I'm thinking that it will make sense to create a class to represent an exclusion object in Google SecOps and then another class to represent the configuration for exclusion objects in a config file. Similar to what we have for rules and reference lists. What do you think?
> 
> Classes for a rule and rule configuration: https://github.com/chronicle/detection-rules/blob/main/tools/rule_manager/rule_cli/rules.py#L53-L85

Oh I see, these basically mirror each other. I can't think of any issues with this (but also haven't reviewed the source code). From an end-user point of view, I think what I would expect from the config file format is something like this...
```yaml
- name: Lab Hosts
  query: (principal.hostname = \"lab-desktop-123\")
  curated_rules:
    - rule_a
    - rule_b
    - rule_z
```

... where each exclusion query is paired with a list of the curated rules it is applied to.

**Comment by threat-punter** [comment]
@jshlbrd – I started working on this code today. I'll let you know when a pull request is ready.

**Comment by threat-punter** [comment]
I've written the code to pull all of my existing rule exclusions from SecOps and write them to a config file like this.

```yaml
Lab Hosts 1:
  archived: false
  create_time: '2025-03-03T16:01:32.286719Z'
  deployment_state_update_time: '2025-03-05T21:37:45.181887Z'
  enabled: true
  exclusion_applications:
    curated_rule_sets:
    - projects/1010101010101/locations/us/instances/32e27911-c58e-4adc-99f1-03652f1a74fd/curatedRuleSetCategories/588c3ec3-15a9-8a7c-b938-1d160912eef7/curatedRuleSets/300eb2a7-99d6-90ae-3ab3-b4842aa9a7cd
    curated_rules:
    - projects/1010101010101/locations/us/instances/32e27911-c58e-4adc-99f1-03652f1a74fd/curatedRules/ur_7f8204c2-0d54-4dab-b7fa-133f8b94a53b
    rules: null
  query: (principal.hostname = "lab-desktop-123") AND (principal.user.userid = /bob/)
  resource_name: projects/1010101010101/locations/us/instances/32e27911-c58e-4adc-99f1-03652f1a74fd/findingsRefinements/fr_1172e8f3-7b49-45ad-ad4f-ef19bb794106
  type: DETECTION_EXCLUSION
  update_time: '2025-03-05T21:37:43.065087Z'
```

I'm working on the code that pushes local updates to SecOps (e.g. creating a new rule exclusion or updating an existing one).

**Comment by threat-punter** [comment]
I just created #105 to add support to retrieve & update rule exclusions in Google SecOps.

Example of retrieving all rule exclusions from SecOps and writing them to a local config file:

```
(venv) python -m rule_cli --pull-latest-rule-exclusions
07-Mar-25 15:23:57 MST | INFO | <module> | Rule CLI started
07-Mar-25 15:23:57 MST | INFO | <module> | Attempting to pull latest version of all rule exclusions from Google SecOps and update local config file
07-Mar-25 15:23:58 MST | INFO | get_remote_rule_exclusions | Retrieved 12 rule exclusions
07-Mar-25 15:23:58 MST | INFO | get_remote_rule_exclusions | Retrieved a total of 12 rule exclusions
07-Mar-25 15:23:58 MST | INFO | get_remote_rule_exclusions | Attempting to retrieve deployment state for 12 rule exclusions
07-Mar-25 15:24:04 MST | INFO | dump_rule_exclusion_config | Writing rule exclusion config to /Users/x/Documents/projects/google-secops-demo-1/rule_exclusions_config.yaml
```

Reviewing an entry in the `rule_exclusions_config.yaml` file:

```
Lab Hosts 1:
  archived: false
  create_time: '2025-03-03T16:01:32.286719Z'
  deployment_state_update_time: '2025-03-07T17:36:47.140591Z'
  enabled: false
  exclusion_applications:
    curated_rule_sets:
    - projects/1234567890123/locations/us/instances/a7bf4d58-4ae4-4f24-b37f-93ff00fe6246/curatedRuleSetCategories/110fa43d-7165-2355-1985-a63b7cdf90e8/curatedRuleSets/07eab257-51fb-b9c5-2040-dd5d6f65ed79
    - projects/1234567890123/locations/us/instances/a7bf4d58-4ae4-4f24-b37f-93ff00fe6246/curatedRuleSetCategories/110fa43d-7165-2355-1985-a63b7cdf90e8/curatedRuleSets/11c505d4-b424-65e3-d918-1a81232cc76b
    - projects/1234567890123/locations/us/instances/a7bf4d58-4ae4-4f24-b37f-93ff00fe6246/curatedRuleSetCategories/110fa43d-7165-2355-1985-a63b7cdf90e8/curatedRuleSets/1bb02b3f-b870-e048-94d6-ad3d08eb2866
    curated_rules:
    - projects/1234567890123/locations/us/instances/a7bf4d58-4ae4-4f24-b37f-93ff00fe6246/curatedRules/ur_7f8204c2-0d54-4dab-b7fa-133f8b94a53b
  query: (principal.hostname = "lab-desktop-1234")
  resource_name: projects/1234567890123/locations/us/instances/a7bf4d58-4ae4-4f24-b37f-93ff00fe6246/findingsRefinements/fr_1172e8f3-7b49-45ad-ad4f-ef19bb794106
  type: DETECTION_EXCLUSION
  update_time: '2025-03-06T21:26:57.766543Z'
```

Example of creating a new rule exclusion. The following entry is added to the `rule_exclusions_config.yaml` file:

```
Lab Hosts 4:
  enabled: true
  exclusion_applications:
    curated_rule_sets:
    - projects/1234567890123/locations/us/instances/a7bf4d58-4ae4-4f24-b37f-93ff00fe6246/curatedRuleSetCategories/110fa43d-7165-2355-1985-a63b7cdf90e8/curatedRuleSets/07eab257-51fb-b9c5-2040-dd5d6f65ed79
    - projects/1234567890123/locations/us/instances/a7bf4d58-4ae4-4f24-b37f-93ff00fe6246/curatedRuleSetCategories/110fa43d-7165-2355-1985-a63b7cdf90e8/curatedRuleSets/11c505d4-b424-65e3-d918-1a81232cc76b
    - projects/1234567890123/locations/us/instances/a7bf4d58-4ae4-4f24-b37f-93ff00fe6246/curatedRuleSetCategories/110fa43d-7165-2355-1985-a63b7cdf90e8/curatedRuleSets/1bb02b3f-b870-e048-94d6-ad3d08eb2866
    curated_rules:
    - projects/1234567890123/locations/us/instances/a7bf4d58-4ae4-4f24-b37f-93ff00fe6246/curatedRules/ur_7f8204c2-0d54-4dab-b7fa-133f8b94a53b
  query: (principal.hostname = "lab-desktop-1234")
  type: DETECTION_EXCLUSION
```

Deploying local rule exclusion updates to SecOps:

(venv) $ python -m rule_cli --update-remote-rule-exclusions
07-Mar-25 15:26:40 MST | INFO | <module> | Rule CLI started
07-Mar-25 15:26:40 MST | INFO | <module> | Attempting to update rule exclusions in Google SecOps based on local config file
07-Mar-25 15:26:40 MST | INFO | update_remote_rule_exclusions | Attempting to update rule exclusions in Google SecOps based on local config file /Users/x/Documents/projects/google-secops-demo-1/rule_exclusions_config.yaml
07-Mar-25 15:26:40 MST | INFO | load_rule_exclusion_config | Loading rule exclusion config file from /Users/x/Documents/projects/google-secops-demo-1/rule_exclusions_config.yaml
07-Mar-25 15:26:40 MST | INFO | load_rule_exclusion_config | Loaded 13 rule exclusion config entries from file /Users/x/Documents/projects/google-secops-demo-1/rule_exclusions_config.yaml
07-Mar-25 15:26:40 MST | INFO | update_remote_rule_exclusions | Attempting to retrieve latest version of all rule exclusions from Google SecOps
07-Mar-25 15:26:40 MST | INFO | get_remote_rule_exclusions | Attempting to retrieve all rule exclusions from Google SecOps
07-Mar-25 15:26:41 MST | INFO | get_remote_rule_exclusions | Retrieved 12 rule exclusions
07-Mar-25 15:26:41 MST | INFO | get_remote_rule_exclusions | Retrieved a total of 12 rule exclusions
07-Mar-25 15:26:41 MST | INFO | get_remote_rule_exclusions | Attempting to retrieve deployment state for 12 rule exclusions
07-Mar-25 15:26:47 MST | INFO | update_remote_rule_exclusions | Checking if any rule exclusion updates are required
07-Mar-25 15:26:48 MST | INFO | update_remote_rule_exclusions | Created new rule exclusion Lab Hosts 4
07-Mar-25 15:26:48 MST | INFO | update_remote_rule_exclusion_state | Rule exclusion Lab Hosts 4 - Enabling rule exclusion
07-Mar-25 15:26:48 MST | INFO | update_remote_rule_exclusion_state | Rule exclusion Lab Hosts 4 - Updating detection exclusion applications
07-Mar-25 15:26:49 MST | INFO | update_remote_rule_exclusions | Logging summary of rule exclusion changes...
07-Mar-25 15:26:49 MST | INFO | update_remote_rule_exclusions | Rule exclusions created: 1
07-Mar-25 15:26:49 MST | INFO | update_remote_rule_exclusions | created rule exclusion ('Lab Hosts 4', 'projects/1234567890123/locations/us/instances/a7bf4d58-4ae4-4f24-b37f-93ff00fe6246/findingsRefinements/fr_42491af6-f607-4044-834a-451b59858358')
07-Mar-25 15:26:49 MST | INFO | update_remote_rule_exclusions | Rule exclusions updated: 0
07-Mar-25 15:26:49 MST | INFO | update_remote_rule_exclusions | Rule exclusions enabled: 1
07-Mar-25 15:26:49 MST | INFO | update_remote_rule_exclusions | enabled rule exclusion ('Lab Hosts 4', 'projects/1234567890123/locations/us/instances/a7bf4d58-4ae4-4f24-b37f-93ff00fe6246/findingsRefinements/fr_42491af6-f607-4044-834a-451b59858358')
07-Mar-25 15:26:49 MST | INFO | update_remote_rule_exclusions | Rule exclusions disabled: 0
07-Mar-25 15:26:49 MST | INFO | update_remote_rule_exclusions | Rule exclusions archived: 0
07-Mar-25 15:26:49 MST | INFO | update_remote_rule_exclusions | Rule exclusions unarchived: 0
07-Mar-25 15:26:49 MST | INFO | update_remote_rule_exclusions | Rule exclusions detection_exclusion_applications_updated: 1
07-Mar-25 15:26:49 MST | INFO | update_remote_rule_exclusions | detection_exclusion_applications_updated rule exclusion 
...
```
